[2024-11-14T12:54:10.079+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-14T12:54:10.104+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_reddit_pipeline.reddit_extraction manual__2024-11-14T12:52:03.757617+00:00 [queued]>
[2024-11-14T12:54:10.118+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_reddit_pipeline.reddit_extraction manual__2024-11-14T12:52:03.757617+00:00 [queued]>
[2024-11-14T12:54:10.119+0000] {taskinstance.py:2866} INFO - Starting attempt 2 of 2
[2024-11-14T12:54:10.140+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): reddit_extraction> on 2024-11-14 12:52:03.757617+00:00
[2024-11-14T12:54:10.148+0000] {standard_task_runner.py:72} INFO - Started process 62 to run task
[2024-11-14T12:54:10.155+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'etl_reddit_pipeline', 'reddit_extraction', 'manual__2024-11-14T12:52:03.757617+00:00', '--job-id', '26', '--raw', '--subdir', 'DAGS_FOLDER/reddit_dag.py', '--cfg-path', '/tmp/tmpjzx9vd7n']
[2024-11-14T12:54:10.158+0000] {standard_task_runner.py:105} INFO - Job 26: Subtask reddit_extraction
[2024-11-14T12:54:10.225+0000] {task_command.py:467} INFO - Running <TaskInstance: etl_reddit_pipeline.reddit_extraction manual__2024-11-14T12:52:03.757617+00:00 [running]> on host 8fb97dcb61a0
[2024-11-14T12:54:10.336+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Arthur Brito' AIRFLOW_CTX_DAG_ID='etl_reddit_pipeline' AIRFLOW_CTX_TASK_ID='reddit_extraction' AIRFLOW_CTX_EXECUTION_DATE='2024-11-14T12:52:03.757617+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-14T12:52:03.757617+00:00'
[2024-11-14T12:54:10.338+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-14T12:54:10.359+0000] {logging_mixin.py:190} INFO - Conectado ao Reddit
[2024-11-14T12:54:12.608+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/pipelines/reddit_pipeline.py", line 13, in reddit_pipeline
    post_df = transform_data(post_df)
  File "/opt/airflow/etls/reddit_etl.py", line 39, in transform_data
    post_df['num_comments'] = np.where(post_df['num_comments'].astype(int))
  File "/home/airflow/.local/lib/python3.9/site-packages/pandas/core/frame.py", line 4311, in __setitem__
    self._set_item(key, value)
  File "/home/airflow/.local/lib/python3.9/site-packages/pandas/core/frame.py", line 4524, in _set_item
    value, refs = self._sanitize_column(value)
  File "/home/airflow/.local/lib/python3.9/site-packages/pandas/core/frame.py", line 5266, in _sanitize_column
    com.require_length_match(value, self.index)
  File "/home/airflow/.local/lib/python3.9/site-packages/pandas/core/common.py", line 573, in require_length_match
    raise ValueError(
ValueError: Length of values (1) does not match length of index (40)
[2024-11-14T12:54:12.631+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=etl_reddit_pipeline, task_id=reddit_extraction, run_id=manual__2024-11-14T12:52:03.757617+00:00, execution_date=20241114T125203, start_date=20241114T125410, end_date=20241114T125412
[2024-11-14T12:54:12.668+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-14T12:54:12.671+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 26 for task reddit_extraction (Length of values (1) does not match length of index (40); 62)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/pipelines/reddit_pipeline.py", line 13, in reddit_pipeline
    post_df = transform_data(post_df)
  File "/opt/airflow/etls/reddit_etl.py", line 39, in transform_data
    post_df['num_comments'] = np.where(post_df['num_comments'].astype(int))
  File "/home/airflow/.local/lib/python3.9/site-packages/pandas/core/frame.py", line 4311, in __setitem__
    self._set_item(key, value)
  File "/home/airflow/.local/lib/python3.9/site-packages/pandas/core/frame.py", line 4524, in _set_item
    value, refs = self._sanitize_column(value)
  File "/home/airflow/.local/lib/python3.9/site-packages/pandas/core/frame.py", line 5266, in _sanitize_column
    com.require_length_match(value, self.index)
  File "/home/airflow/.local/lib/python3.9/site-packages/pandas/core/common.py", line 573, in require_length_match
    raise ValueError(
ValueError: Length of values (1) does not match length of index (40)
[2024-11-14T12:54:12.712+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-11-14T12:54:12.736+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-14T12:54:12.747+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
